### ISSUE TITLE
Publish package to Python package index

### ISSUE THREAD

**Issue by hickford** [jaredks/pyprimesieve#2]
This library sounds great. Please could you publish a package to the Python package index? https://pypi.python.org/pypi

Then add installation instructions to the readme

    pip install pyprimesieve

**Comment by hickford** [comment]
@jaredks Hi Jared, any progress? This would make it easier for software that depends on the library. Any objection if I publish a fork to PyPI?

**Comment by jaredks** [comment]
@hickford Made some changes for pypi and bumped the version. Indeed there were a few snags for C extensions I hadn't dealt with before. Should be working now.

**Comment by hickford** [comment]
Brilliant, thanks very much. I use the library frequently to solve Google Code Jam problems
